-- Seed ~98 US metros into search_locations (engine reads this table for its geo pool).
-- Med-spa-heavy markets weighted; HI/AK excluded. Applied live.
insert into search_locations (location, country, active) values
  ('New York, NY, USA', 'US', true),
  ('Los Angeles, CA, USA', 'US', true),
  ('Chicago, IL, USA', 'US', true),
  ('Houston, TX, USA', 'US', true),
  ('Phoenix, AZ, USA', 'US', true),
  ('Philadelphia, PA, USA', 'US', true),
  ('San Antonio, TX, USA', 'US', true),
  ('San Diego, CA, USA', 'US', true),
  ('Dallas, TX, USA', 'US', true),
  ('Austin, TX, USA', 'US', true),
  ('San Jose, CA, USA', 'US', true),
  ('Fort Worth, TX, USA', 'US', true),
  ('Jacksonville, FL, USA', 'US', true),
  ('Columbus, OH, USA', 'US', true),
  ('Charlotte, NC, USA', 'US', true),
  ('Indianapolis, IN, USA', 'US', true),
  ('San Francisco, CA, USA', 'US', true),
  ('Seattle, WA, USA', 'US', true),
  ('Denver, CO, USA', 'US', true),
  ('Washington, DC, USA', 'US', true),
  ('Nashville, TN, USA', 'US', true),
  ('Boston, MA, USA', 'US', true),
  ('El Paso, TX, USA', 'US', true),
  ('Portland, OR, USA', 'US', true),
  ('Las Vegas, NV, USA', 'US', true),
  ('Detroit, MI, USA', 'US', true),
  ('Memphis, TN, USA', 'US', true),
  ('Louisville, KY, USA', 'US', true),
  ('Baltimore, MD, USA', 'US', true),
  ('Milwaukee, WI, USA', 'US', true),
  ('Albuquerque, NM, USA', 'US', true),
  ('Tucson, AZ, USA', 'US', true),
  ('Fresno, CA, USA', 'US', true),
  ('Sacramento, CA, USA', 'US', true),
  ('Mesa, AZ, USA', 'US', true),
  ('Kansas City, MO, USA', 'US', true),
  ('Atlanta, GA, USA', 'US', true),
  ('Omaha, NE, USA', 'US', true),
  ('Colorado Springs, CO, USA', 'US', true),
  ('Raleigh, NC, USA', 'US', true),
  ('Miami, FL, USA', 'US', true),
  ('Long Beach, CA, USA', 'US', true),
  ('Virginia Beach, VA, USA', 'US', true),
  ('Oakland, CA, USA', 'US', true),
  ('Minneapolis, MN, USA', 'US', true),
  ('Tulsa, OK, USA', 'US', true),
  ('Tampa, FL, USA', 'US', true),
  ('Arlington, TX, USA', 'US', true),
  ('New Orleans, LA, USA', 'US', true),
  ('Wichita, KS, USA', 'US', true),
  ('Cleveland, OH, USA', 'US', true),
  ('Bakersfield, CA, USA', 'US', true),
  ('Aurora, CO, USA', 'US', true),
  ('Anaheim, CA, USA', 'US', true),
  ('Santa Ana, CA, USA', 'US', true),
  ('Riverside, CA, USA', 'US', true),
  ('Corpus Christi, TX, USA', 'US', true),
  ('Lexington, KY, USA', 'US', true),
  ('Henderson, NV, USA', 'US', true),
  ('Stockton, CA, USA', 'US', true),
  ('Saint Paul, MN, USA', 'US', true),
  ('Cincinnati, OH, USA', 'US', true),
  ('Pittsburgh, PA, USA', 'US', true),
  ('Greensboro, NC, USA', 'US', true),
  ('Plano, TX, USA', 'US', true),
  ('Orlando, FL, USA', 'US', true),
  ('Irvine, CA, USA', 'US', true),
  ('Newark, NJ, USA', 'US', true),
  ('Durham, NC, USA', 'US', true),
  ('Toledo, OH, USA', 'US', true),
  ('Fort Wayne, IN, USA', 'US', true),
  ('St. Petersburg, FL, USA', 'US', true),
  ('Chandler, AZ, USA', 'US', true),
  ('Madison, WI, USA', 'US', true),
  ('Scottsdale, AZ, USA', 'US', true),
  ('Buffalo, NY, USA', 'US', true),
  ('Gilbert, AZ, USA', 'US', true),
  ('Glendale, AZ, USA', 'US', true),
  ('Reno, NV, USA', 'US', true),
  ('Boise, ID, USA', 'US', true),
  ('Richmond, VA, USA', 'US', true),
  ('Spokane, WA, USA', 'US', true),
  ('Frisco, TX, USA', 'US', true),
  ('Charleston, SC, USA', 'US', true),
  ('Naples, FL, USA', 'US', true),
  ('Boca Raton, FL, USA', 'US', true),
  ('West Palm Beach, FL, USA', 'US', true),
  ('Fort Lauderdale, FL, USA', 'US', true),
  ('Santa Monica, CA, USA', 'US', true),
  ('Beverly Hills, CA, USA', 'US', true),
  ('Pasadena, CA, USA', 'US', true),
  ('Fort Collins, CO, USA', 'US', true),
  ('Salt Lake City, UT, USA', 'US', true),
  ('Des Moines, IA, USA', 'US', true),
  ('Little Rock, AR, USA', 'US', true),
  ('Birmingham, AL, USA', 'US', true),
  ('Columbia, SC, USA', 'US', true),
  ('Knoxville, TN, USA', 'US', true)
on conflict do nothing;
